# Las competencias en ecografía

Como cualquier técnica de radiología, la ecografía tiene una fase de adquisición de imágenes y otra de informe del estudio. Habitualmente, los técnicos obtienen las imágenes y los radiólogos las informan. Sin embargo, en la ecografía se asume que la adquisición y el informe son dos procesos paralelos casi simultáneos y que ambas deberian ser hechas por el mismo profesional (radiólogo). 

Sin embargo, no todas las ecografías son iguales. Algunas (como la ecografía cervical, la ecografía escrotal, la ecografía de caderas del neonato, los Doppler venoso de miembros inferiores o  carotídeo…) pueden estandarizarse con una serie de procedimientos que permitan que **siempre se adquieran las mismas imágenes, con los mismos criterios**, algo que se hace en la TC o la RM. En estos casos, se pueden definir los criterios para adquirir la competencia. En algunos casos, como la ecografía de abdomen, es difícil obtener unas imágenes estandarizadas y, por lo tanto, conseguir que la adquisición de imágenes y el informe de las imágenes se haga en dos fases diferentes. 

Por estos motivos, es importante definir las **competencias en la adquisición de las ecografías**. La idea es definir una serie de pruebas que se puedan estandarizar y determinar los criterios de adquisición para su realización. Como ejemplo, la *ecografía cervical*. Es una técnica fácil de estandarizar, en la que se organiza a definir qué imágenes hay que incluir, con sus criterios de calidad. Esto hace que la ecografía cervical sea un ejemplo de posible formación específica y de adquisición de competencias. 
