# Alternativas

Dado que la situación no es sostenible, hay que buscar soluciones:

 - **Controlar la demanda**: se va a trabajar en el tema, especialmente con los médicos de atención primaria. Es de esperar que esta medida tenga poco impacto y, el que tenga, tardará en verse.
* **Dejar que otros hagan las ecografías**: esto es lo que está pasando. Con la excusa de la demora, algunos servicios están empezando a hacer estudios ecográficos. La inversión es escasa y con esto justifican la reestructuración de su actividad. Sin embargo, es probable queesta actividad no tenga impacto en las listas de espera, porque las peticiones de ecografías no las van a limitar. Y no solo esto, sino que está descrito que cuando médicos no radiólogos empiezan a hacer ecografías, la demanda aumenta. Como es de esperar, esto no lo cuentan así a las direcciones correspondientes. El tema se “vende” como que si ellos empiezan a hacer ecografías, va a mejorar la lista de espera. La realidad no creo que sea así, pero es muy difícil de argumentar y de discutir en Dirección. 
* **Optimizar la producción**: consiste en optimizar la capacidad de realización de estudios de las salas del área. Para ello, además de poder hacer actividad extra, se propone que los técnicos puedan hacer ecografías, controladas y supervisadas por los radiólogos.

