# Comentarios

La ecografía siempre se define como una técnica “explorador dependiente” y muy variable. Esto es así en un porcentaje de estudios ecográficos, pero no en todos. Los radiólogos estamos acostumbrados a adquirir la imagen y, al mismo tiempo, ir elaborando mentalmente el informe. Por ello, nos hemos acostumbrado a hacer unos estudios poco sistemáticos, enfocados a recoger las imágenes que consideramos más relevantes para nuestro diagnóstico. Esta forma de trabajar tiene muchas ventajas y ha permitido que la ecografía en manos de radiólogos expertos sea una técnica de gran rendimiento diagnóstico.

Sin embargo, no todas las ecografías son iguales, y no todas requieren la misma pericia a la hora de adquirir imágenes. Algunos estudios (como la ecografía cervical) son muy rutinarios y de fácil estandarización. Además, suelen ser poco gratificantes para el radiólogo, que ve más útil dedicar su tiempo a diagnosticar casos complejos con la ecografía en vez de medir dimensiones de una glándula tiroidea o adquirir imágenes de nódulos tiroideos. En estos casos, y solo en estos, y después de un periodo de formación riguroso, con definición de las competencias específicas, los técnicos pueden ser de gran ayuda. 
